my_project:
  outputs:
    dev:
      dataset: yfinance_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:/Users/nbyin/.gc/credentials/google_credentials.json
      location: us-central1
      method: service-account
      priority: interactive
      project: yahoo-finance-455223
      threads: 1
      type: bigquery
  target: dev
